# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.define "master", autostart: true do |master|
    master.vm.hostname = "puppetmaster"
    master.vm.network "private_network", ip: "192.168.147.20", virtualbox__intnet: true
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "768"
    end
    master.vm.provision "shell", inline: <<-SHELL
      sudo su -

      wget http://apt.puppet.com/puppet7-release-bullseye.deb
      dpkg -i puppet7-release-bullseye.deb
      apt-get update
      apt-get --yes install puppetserver pdk
      sed --in-place "s/-Xms2g/-Xms512m/" /etc/default/puppetserver
      sed --in-place "s/-Xmx2g/-Xmx512m/" /etc/default/puppetserver
      rm -f /etc/resolv.conf
      
      source /etc/profile.d/puppet-agent.sh
      puppet config set server puppetmaster --section main
      puppet config set autosign true --section server
      systemctl start puppetserver

      echo "puppetslave" | tee /etc/puppetlabs/puppet/autosign.conf
    SHELL
  end

  config.vm.define "slave", autostart: true do |slave|
    slave.vm.hostname = "puppetslave"
    slave.vm.network "private_network", ip: "192.168.147.21", virtualbox__intnet: true
    slave.vm.provision "shell", inline: <<-SHELL
      sudo su -

      wget http://apt.puppet.com/puppet7-release-bullseye.deb
      dpkg -i puppet7-release-bullseye.deb
      apt-get update
      apt-get install puppet-agent
      /opt/puppetlabs/bin/puppet resource service puppet ensure=running enable=true
      rm -f /etc/resolv.conf
      
      source /etc/profile.d/puppet-agent.sh
      puppet config set server puppetmaster --section main
      echo "192.168.147.20 puppetmaster" | sudo tee --append /etc/hosts
      puppet agent --test
    SHELL
  end

end
