# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.define "master", autostart: true do |master|
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    master.vm.provision "shell", inline: <<-SHELL
      sudo wget http://apt.puppet.com/puppet7-release-bullseye.deb
      sudo dpkg -i puppet7-release-bullseye.deb
      sudo apt-get update
      sudo apt-get --yes install puppetserver pdk
      sudo sed --in-place "s/-Xms2g/-Xms512m/" /etc/default/puppetserver
      sudo sed --in-place "s/-Xmx2g/-Xmx512m/" /etc/default/puppetserver
    SHELL
  end

  config.vm.define "slave", autostart: true do |slave|
    slave.vm.provision "shell", inline: <<-SHELL
      sudo wget http://apt.puppet.com/puppet7-release-bullseye.deb
      sudo dpkg -i puppet7-release-bullseye.deb
      sudo apt-get update
      sudo apt-get install puppet-agent
    SHELL
  end

end
