# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.define "master", autostart: true do |master|
    master.vm.box = "puppet/master"
    master.vm.hostname = "puppetmaster"
    master.vm.network "private_network", ip: "192.168.147.20", virtualbox__intnet: true
    master.vm.provision "shell", inline: <<-SHELL
      sudo su -
      rm -f /etc/resolv.conf
      puppet config set server puppetmaster --section main
      puppet config set autosign true --section server
      echo "puppetslave" | tee /etc/puppetlabs/puppet/autosign.conf
      systemctl start puppetserver
    SHELL
  end

  config.vm.define "slave", autostart: true do |slave|
    slave.vm.box = "puppet/slave"
    slave.vm.hostname = "puppetslave"
    slave.vm.network "private_network", ip: "192.168.147.21", virtualbox__intnet: true
    slave.vm.provision "shell", inline: <<-SHELL
      sudo su -
      rm -f /etc/resolv.conf
      puppet config set server puppetmaster --section main
      echo "192.168.147.20 puppetmaster" | sudo tee --append /etc/hosts
      puppet agent --test
    SHELL
  end

end
